export const seedProducts = [
  {
    id: "serum-01",
    name: "Vitamin C Face Serum",
    description: "Brightening skincare serum suitable for gifting",
    category: "skincare",
    price: 799,
    currency: "INR",
    inventory: 24,
    tags: ["gift", "brightening", "vegan"],
    complements: ["gift-wrap-01", "face-mask-01"],
    shippingDays: 2,
    returnable: true
  },
  {
    id: "cream-01",
    name: "Night Repair Cream",
    description: "Hydrating night moisturiser for dry skin",
    category: "skincare",
    price: 1299,
    currency: "INR",
    inventory: 8,
    tags: ["hydrating", "gift"],
    complements: ["gift-wrap-01", "face-mask-01"],
    shippingDays: 3,
    returnable: true
  },
  {
    id: "gift-set-01",
    name: "Glow Ritual Gift Set",
    description: "A cleanser, serum and moisturiser skincare gift set",
    category: "skincare",
    price: 1899,
    currency: "INR",
    inventory: 5,
    tags: ["gift", "bundle", "premium"],
    complements: ["gift-wrap-01"],
    shippingDays: 2,
    returnable: false
  },
  {
    id: "cleanser-01",
    name: "Gentle Daily Cleanser",
    description: "Fragrance-free cleanser for sensitive skin",
    category: "skincare",
    price: 499,
    currency: "INR",
    inventory: 0,
    tags: ["sensitive", "fragrance-free"],
    complements: ["face-mask-01"],
    shippingDays: 2,
    returnable: true
  },
  {
    id: "gift-wrap-01",
    name: "Reusable Gift Wrap",
    description: "Premium reusable packaging with a handwritten note",
    category: "accessories",
    price: 199,
    currency: "INR",
    inventory: 40,
    tags: ["gift", "packaging"],
    complements: ["serum-01", "cream-01", "gift-set-01"],
    shippingDays: 0,
    returnable: false
  },
  {
    id: "face-mask-01",
    name: "Hydrating Sheet Mask",
    description: "A single-use hydration add-on for a self-care routine",
    category: "skincare",
    price: 299,
    currency: "INR",
    inventory: 30,
    tags: ["hydrating", "add-on"],
    complements: ["serum-01", "cream-01", "cleanser-01"],
    shippingDays: 2,
    returnable: false
  }
];
